# Generated by Django 4.0.6 on 2022-08-18 11:09

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_issuedbook_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returned_book',
            name='return_date',
            field=models.DateField(default=books.models.get_return_date),
        ),
    ]
